version_df_maps = {
    "真":["maimai PLUS","maimai"],
    "超":["maimai GreeN"],
    "檄":["maimai GreeN PLUS"],
    "橙":["maimai ORANGE"],
    "晓":["maimai ORANGE PLUS"],
    "桃":["maimai PiNK"],
    "樱":["maimai PiNK PLUS"],
    "紫":["maimai MURASAKi"],
    "堇":["maimai MURASAKi PLUS"],
    "白":["maimai MiLK"],
    "雪":["MiLK PLUS"],
    "辉":["maimai FiNALE"],
    "熊":["maimai でらっくす"],
    "华":["maimai でらっくす"],
    "爽":["maimai でらっくす Splash"],
    "煌":["maimai でらっくす Splash"],
    "宙":["maimai でらっくす UNiVERSE"],
    "星":["maimai でらっくす UNiVERSE"],
    "祭":["maimai でらっくす FESTiVAL"],
    "祝":["maimai でらっくす FESTiVAL"],
    "舞": ["maimai PLUS", "maimai", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS","maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", "MiLK PLUS","maimai FiNALE"],
    "霸": ["maimai PLUS", "maimai", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS","maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", "MiLK PLUS","maimai FiNALE"]
}

version_ez_map = {
    "maimai": "真",
    "PLUS":"真",
    "GreeN":"超",
    "GreeN PLUS":"檄",
    "ORANGE":"橙",
    "ORANGE PLUS":"暁",
    "PiNK":"桃",
    "PiNK PLUS":"櫻",
    "MURASAKi":"紫",
    "MURASAKi PLUS":"菫",
    "MiLK":"白",
    "MiLK PLUS":"雪",
    "FiNALE":"輝",
    "FiNALE":"辉",
    "舞萌DX":"熊、華",
    "舞萌DX 2021":"爽、煌",
    "舞萌DX 2022":"宙、星",
    "舞萌DX 2023":"祭、祝"
}